FROM node:18 AS build

WORKDIR /app

COPY ./package.json ./package-lock.json ./

RUN npm install

COPY ./frontend ./

RUN npm install react-router-dom

RUN npm run build

RUN rm -rf /app/node_modules

FROM nginx:alpine AS production

COPY --from=build /app/dist /usr/share/nginx/html

COPY ./frontend/nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
