# Use a Python 3.9 slim image
FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --no-cache-dir -r requirements.txt

COPY ./backend /app/

RUN rm -rf /app/.venv /app/backend/__pycache__ /app/backend/instance

EXPOSE 5000

ENV FLASK_APP=app
ENV FLASK_ENV=development

# Start the Flask app
CMD ["flask", "run", "--host=0.0.0.0"]
